# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.alarm_controller_api import AlarmControllerApi


class TestAlarmControllerApi(unittest.TestCase):
    """ AlarmControllerApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.alarm_controller_api.AlarmControllerApi()

    def tearDown(self):
        pass

    def test_ack_alarm_using_post(self):
        """
        Test case for ack_alarm_using_post

        ackAlarm
        """
        pass

    def test_clear_alarm_using_post(self):
        """
        Test case for clear_alarm_using_post

        clearAlarm
        """
        pass

    def test_get_alarm_by_id_using_get(self):
        """
        Test case for get_alarm_by_id_using_get

        getAlarmById
        """
        pass

    def test_get_alarm_info_by_id_using_get(self):
        """
        Test case for get_alarm_info_by_id_using_get

        getAlarmInfoById
        """
        pass

    def test_get_alarms_using_get(self):
        """
        Test case for get_alarms_using_get

        getAlarms
        """
        pass

    def test_get_highest_alarm_severity_using_get(self):
        """
        Test case for get_highest_alarm_severity_using_get

        getHighestAlarmSeverity
        """
        pass

    def test_save_alarm_using_post(self):
        """
        Test case for save_alarm_using_post

        saveAlarm
        """
        pass


if __name__ == '__main__':
    unittest.main()
