# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.text_page_data_asset import TextPageDataAsset


class TestTextPageDataAsset(unittest.TestCase):
    """ TextPageDataAsset unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextPageDataAsset(self):
        """
        Test TextPageDataAsset
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.text_page_data_asset.TextPageDataAsset()
        pass


if __name__ == '__main__':
    unittest.main()
