# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.plugin_controller_api import PluginControllerApi


class TestPluginControllerApi(unittest.TestCase):
    """ PluginControllerApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.plugin_controller_api.PluginControllerApi()

    def tearDown(self):
        pass

    def test_activate_plugin_by_id_using_post(self):
        """
        Test case for activate_plugin_by_id_using_post

        activatePluginById
        """
        pass

    def test_delete_plugin_using_delete(self):
        """
        Test case for delete_plugin_using_delete

        deletePlugin
        """
        pass

    def test_get_plugin_by_id_using_get(self):
        """
        Test case for get_plugin_by_id_using_get

        getPluginById
        """
        pass

    def test_get_plugin_by_token_using_get(self):
        """
        Test case for get_plugin_by_token_using_get

        getPluginByToken
        """
        pass

    def test_get_plugins_using_get(self):
        """
        Test case for get_plugins_using_get

        getPlugins
        """
        pass

    def test_get_system_plugins_using_get(self):
        """
        Test case for get_system_plugins_using_get

        getSystemPlugins
        """
        pass

    def test_get_tenant_plugins_using_get(self):
        """
        Test case for get_tenant_plugins_using_get

        getTenantPlugins
        """
        pass

    def test_get_tenant_plugins_using_get1(self):
        """
        Test case for get_tenant_plugins_using_get1

        getTenantPlugins
        """
        pass

    def test_save_plugin_using_post(self):
        """
        Test case for save_plugin_using_post

        savePlugin
        """
        pass

    def test_suspend_plugin_by_id_using_post(self):
        """
        Test case for suspend_plugin_by_id_using_post

        suspendPluginById
        """
        pass


if __name__ == '__main__':
    unittest.main()
