# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.user_controller_api import UserControllerApi


class TestUserControllerApi(unittest.TestCase):
    """ UserControllerApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.user_controller_api.UserControllerApi()

    def tearDown(self):
        pass

    def test_delete_user_using_delete(self):
        """
        Test case for delete_user_using_delete

        deleteUser
        """
        pass

    def test_get_activation_link_using_get(self):
        """
        Test case for get_activation_link_using_get

        getActivationLink
        """
        pass

    def test_get_customer_users_using_get(self):
        """
        Test case for get_customer_users_using_get

        getCustomerUsers
        """
        pass

    def test_get_tenant_admins_using_get(self):
        """
        Test case for get_tenant_admins_using_get

        getTenantAdmins
        """
        pass

    def test_get_user_by_id_using_get(self):
        """
        Test case for get_user_by_id_using_get

        getUserById
        """
        pass

    def test_save_user_using_post(self):
        """
        Test case for save_user_using_post

        saveUser
        """
        pass

    def test_send_activation_email_using_post(self):
        """
        Test case for send_activation_email_using_post

        sendActivationEmail
        """
        pass


if __name__ == '__main__':
    unittest.main()
