# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.event_controller_api import EventControllerApi


class TestEventControllerApi(unittest.TestCase):
    """ EventControllerApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.event_controller_api.EventControllerApi()

    def tearDown(self):
        pass

    def test_get_events_using_get(self):
        """
        Test case for get_events_using_get

        getEvents
        """
        pass

    def test_get_events_using_get1(self):
        """
        Test case for get_events_using_get1

        getEvents
        """
        pass


if __name__ == '__main__':
    unittest.main()
